### PR TITLE
updated packages

### PR DESCRIPTION
**Pull request by miyamoto-san**

### CODE REVIEW

**Comment by kaj** [comment]
Wow, a package-lock.json that is almost a thousand lines shorter is clearly an improvement!  But the changes in vscode and the app itselt isn't really related to the updates, are they?

**Comment by exacs** [comment]
This is still not mergeable. Rasmus said that the *change* in `module-selector.js` is not part of the branch but the file itself must be present with the old code, not deleted!

Same with the changes in the file `.vscode/settings.json`. Can you revert the changes in that file?

**Comment by miyamoto-san** [comment]
> This is still not mergeable. Rasmus said that the _change_ in `module-selector.js` is not part of the branch but the file itself must be present with the old code, not deleted!...

I'll merge my `ladok-module-auto-select-if-one-option` branch into this one as soon as it's approved and that should sort it out!

**Comment by kaj** [comment]
This PR updates ava from 2.4.0 to 3.11.1, while #76 removes it entirely.  So maybe we should just close this in favor of that?

**Pull request closed without merging**
